name: CI

on:
  push:
    branch: [mdoc]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: ${{ github.ref }}
      - name: update
        shell: bash 
        run: |
           cd ${{ github.ref }}
           CBRH=$(git rev-parse --abbrev-ref HEAD)
           git config pull.rebase false
           git config --local user.email "bot@users.noreply.github.com"
           git config --local user.name "bot"
           git fetch origin books:books
           git checkout books
           git checkout -b doc
           mkdir /tmp/docs
           mv * /tmp/docs
           mv /tmp/docs .
           find . -name "*htm" > /tmp/todo
           while IFS= read -r line
           do
             iconv -f GB18030 -t utf-8 "$line" > "${line}.txt" && mv "$line.txt" "$line" || echo "$line" &
           done < /tmp/todo
           mv /tmp/todo book.md
           git add -A .
           git commit -m "fix encoding"
           git push "https://${GITHUB_ACTOR}:${{ github.token }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:doc
